server:
  port: 8085 # 端口

spring:
  application:
    name: ms-feeds # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/db_imooc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&&allowPublicKeyRetrieval=true
  # Redis
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    database: 2
  # Swagger
  swagger:
    base-package: com.imooc.feeds
    title: 慕课美食社交食客API接口文档

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://pc-sony:8080/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
  level:
    com.imooc.feeds.mapper: debug
#    com.imooc.oauth2.client.Oauth2ServerClient: debug
#
#feign:
#  client:
#    config:
#      default:
#        logger-level: full
